version = 1

[[analyzers]]
name = "javascript"
  [analyzers.meta]
  plugins = [
    "angular"  # Cambia por "react" o "vue" si corresponde, o agrega más de uno si usas varios frameworks
  ]
  environment = ["nodejs"]

[[analyzers]]
name = "test-coverage"
enabled = true
  [analyzers.meta]
  reports = [
    "coverage/lcov.info"
  ]

exclude = [
  "node_modules/**/*",
  "dist/**/*",
  "build/**/*",
  "coverage/**/*",
  "vendor/**/*"
]
