version = 1

[[analyzers]]
name = "javascript"
  [analyzers.meta]
  plugins = [
    "angular"   # Cambia por "react" o "vue" según tu stack
  ]
  environment = ["nodejs"]

exclude = [
  "node_modules/**/*",
  "dist/**/*",
  "build/**/*",
  "coverage/**/*",
  "vendor/**/*"
]
